=== Nuix/jrawio-src/jrawio/src/main/metadata/Directory.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
    <xsd:element name="directory">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="tag" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="code">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:nonNegativeInteger">
                                            <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="type">  
                                <xsd:simpleType>                                    
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="byte"/>
                                        <xsd:enumeration value="signed byte"/>
                                        <xsd:enumeration value="short"/>
                                        <xsd:enumeration value="signed short"/>
                                        <xsd:enumeration value="int"/>
                                        <xsd:enumeration value="signed int"/>
                                        <xsd:enumeration value="long"/>
                                        <xsd:enumeration value="signed long"/>
                                        <xsd:enumeration value="float"/>
                                        <xsd:enumeration value="double"/>
                                        <xsd:enumeration value="rational"/>
                                        <xsd:enumeration value="signed rational"/>
                                        <xsd:enumeration value="ascii"/>
                                        <xsd:enumeration value="undefined"/>
                                    </xsd:restriction> 
                                </xsd:simpleType>
                            </xsd:element>            
                            <xsd:element name="length" type="xsd:positiveInteger"  minOccurs="0"/>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="example" type="xsd:string"/>
                            <xsd:element name="models" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="model" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="enumeration" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="item" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="value">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="identifier" type="xsd:string"  minOccurs="0"/>
                                                    <xsd:element name="short-description" type="xsd:string"  minOccurs="0"/>
                                                    <xsd:element name="description" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="bitmask" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="item" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="value">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="identifier" type="xsd:string"/>
                                                    <xsd:element name="short-description" type="xsd:string"/>
                                                    <xsd:element name="description" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="description" type="xsd:string"/>
                        </xsd:sequence>
                        <xsd:attribute name="status" default="good">  
                            <xsd:simpleType>                                    
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="unknown"/>
                                    <xsd:enumeration value="uncertain"/>
                                    <xsd:enumeration value="incomplete"/>
                                    <xsd:enumeration value="volatile"/>
                                    <xsd:enumeration value="good"/>
                                </xsd:restriction> 
                            </xsd:simpleType>
                        </xsd:attribute>            
                    </xsd:complexType>
                </xsd:element>                
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nuix/jrawio-src/jrawio-src/metadata/MinoltaMakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2006 by OpenRAW (http://www.openraw.org)
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="Minolta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>0</code>
        <type>undefined</type>
        <length>4</length>
        <name>Block Descriptor</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>1</code>
        <type>undefined</type>
        <length>99</length>
        <name>Camera Settings</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>16</code>
        <type>undefined</type>
        <length>99</length>
        <name>Autofocus Related</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>32</code>
        <type>undefined</type>
        <length>99</length>
        <name>Unknown</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>64</code>
        <type>long</type>
        <length>1</length>
        <name>Raster Data Size</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>129</code>
        <type>long</type>
        <length>1</length>
        <name>Thumbnail</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>3584</code>
        <type>undefined</type>
        <length>40</length>
        <name>Epson PIM Info</name>
        <example></example>
        <description></description>
    </tag>
</directory>

=== Nuix/jrawio-src/jrawio/src/main/metadata/SonyMakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="SonySRF" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>0</code>
        <type>long</type>
        <length>1</length>
        <name>SRF2 Key</name>
        <example></example>
        <description>The key needed for deciphering the SRF2 IFD.</description>
    </tag>
    <tag>
        <code>1</code>
        <type>long</type>
        <length>1</length>
        <name>Raster Key</name>
        <example></example>
        <description>The key needed for deciphering the raster data.</description>
    </tag>
    <tag>
        <code>4</code>
        <type>long</type>
        <length>1</length>
        <name>Raster Offset</name>
        <example></example>
        <description>The offset of raster data.</description>
    </tag>
    <tag>
        <code>5</code>
        <type>long</type>
        <length>1</length>
        <name>Raster Byte Count</name>
        <example></example>
        <description>The size of raster data in bytes.</description>
    </tag>
 </directory>

=== Nuix/jrawio-src/jrawio/src/main/metadata/CanonCR2MakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->

<directory name="CanonCR2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>6</code>
        <type>ascii</type>
        <name>Camera Model</name>
        <example>Canon EOS-1Ds Mark II</example>
        <description>The camera model name. The value can be padded with spaces and/or zeroes.</description>
    </tag>
    <tag>
        <code>7</code>
        <type>ascii</type>
        <name>Firmware Version</name>
        <example>Firmware Version 1.0.2</example>
        <description>The version of the camera firmware. The value can be padded with spaces and/or zeroes.</description>
    </tag>
    <tag>
        <code>9</code>
        <type>ascii</type>
        <name>Owner Name</name>
        <example>John Smith</example>
        <description>The name of the camera owner. The value can be padded with spaces and/or zeroes.</description>
    </tag>
    <tag>
        <code>12</code>
        <type>long</type>
        <length>1</length>
        <name>Serial Number</name>
        <example>303949</example>
        <description>The serial number.</description>
    </tag>
    <tag>
        <code>18</code>
        <type>short</type>
        <length>99</length>
        <name>Canon Picture Info</name>
        <example></example>
        <description>A block of data related to the picture.</description>
    </tag>
    <tag>
        <code>224</code>
        <type>short</type>
        <length>99</length>
        <name>Sensor Info</name>
        <example></example>
        <description>A block of data related to the sensor.</description>
    </tag>
    <tag>
        <code>16385</code>
        <type>short</type>
        <length></length>
        <name>White Balance Info</name>
        <example></example>
        <description>A block of data related to the white balance.</description>
    </tag>
 </directory>

=== Nuix/jrawio-src/jrawio/src/main/metadata/OlympusMakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="Olympus" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>256</code>
        <type>undefined</type>
        <length>99</length>
        <name>JpegThumbnail</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>512</code>
        <type>long</type>
        <length>3</length>
        <name>SpecialMode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>521</code>
        <type>undefined</type>
        <length>99</length>
        <name>CameraID</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>8208</code>
        <type>int</type>
        <length>1</length>
        <name>Equipment</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>8224</code>
        <type>int</type>
        <length>1</length>
        <name>CameraSettings</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>8240</code>
        <type>int</type>
        <length>1</length>
        <name>RawDevelopment</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>8256</code>
        <type>int</type>
        <length>1</length>
        <name>ImageProcessing</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>8272</code>
        <type>int</type>
        <length>1</length>
        <name>FocusInfo</name>
        <example></example>
        <description></description>
    </tag>
</directory>

=== Nuix/jrawio-src/jrawio/metadata/OlympusMakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2006 by OpenRAW (http://www.openraw.org)
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="Olympus" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>0</code>
        <type>ascii</type>
        <name>Makernote Version</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>1</code>
        <type>undefined</type>
        <name>Camera Settings</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>3</code>
        <type>undefined</type>
        <name>Alternate Camera Settings</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>64</code>
        <type>undefined</type>
        <name>Compressed Image Size</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>129</code>
        <type>int</type>
        <length>1</length>
        <name>Minolta Thumbnail Offset</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>136</code>
        <type>int</type>
        <length>1</length>
        <name>Alternate Minolta Thumbnail Offset</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>137</code>
        <type>int</type>
        <length>1</length>
        <name>Minolta Thumbnail Length</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>257</code>
        <type>short</type>
        <length>1</length>
        <name>Colour Mode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>258</code>
        <type>short</type>
        <length>1</length>
        <name>Image Quality</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>259</code>
        <type>short</type>
        <length>1</length>
        <name>Alternate Image Quality</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>512</code>
        <type>long</type>
        <length>3</length>
        <name>Special Mode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>513</code>
        <type>short</type>
        <length>1</length>
        <name>JPEG Quality</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>514</code>
        <type>short</type>
        <length>1</length>
        <name>Macro</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>516</code>
        <type>rational</type>
        <length>1</length>
        <name>Digital Zoom</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>519</code>
        <type>ascii</type>
        <name>Firmware Version</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>520</code>
        <type>ascii</type>
        <name>Picture Info Data</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>521</code>
        <type>ascii</type>
        <name>Camera ID</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>523</code>
        <type>int</type>
        <length>1</length>
        <name>Image Width</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>524</code>
        <type>int</type>
        <length>1</length>
        <name>Image Height</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>525</code>
        <type>ascii</type>
        <name>Original Manufacturer Model</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>3584</code>
        <type>undefined</type>
        <name>Print Image Matching Info</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4100</code>
        <type>int</type>
        <length>1</length>
        <name>Flash Mode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4102</code>
        <type>int</type>
        <length>1</length>
        <name>Bracket</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4107</code>
        <type>int</type>
        <length>1</length>
        <name>Focus Mode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4108</code>
        <type>int</type>
        <length>1</length>
        <name>Focus Distance</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4109</code>
        <type>int</type>
        <length>1</length>
        <name>Zoom</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4110</code>
        <type>int</type>
        <length>1</length>
        <name>Macro Focus</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4111</code>
        <type>short</type>
        <length>1</length>
        <name>Sharpness</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4113</code>
        <type>short</type>
        <length>9</length>
        <name>Colour Matrix</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4114</code>
        <type>short</type>
        <length>4</length>
        <name>Black Level</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4117</code>
        <type>short</type>
        <length>1</length>
        <name>White Balance</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4119</code>
        <type>short</type>
        <length>2</length>
        <name>Red Bias</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4120</code>
        <type>short</type>
        <length>2</length>
        <name>Blue Bias</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4122</code>
        <type>short</type>
        <length>1</length>
        <name>Serial Number</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4131</code>
        <type>short</type>
        <length>1</length>
        <name>Flash Bias</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4137</code>
        <type>short</type>
        <length>1</length>
        <name>Contrast</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4138</code>
        <type>short</type>
        <length>1</length>
        <name>Sharpness Factor</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4139</code>
        <type>short</type>
        <length>1</length>
        <name>Colour Control</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4140</code>
        <type>short</type>
        <length>1</length>
        <name>Valid Bits</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4141</code>
        <type>short</type>
        <length>1</length>
        <name>Coring Filter</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4142</code>
        <type>long</type>
        <length>1</length>
        <name>Final Width</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4143</code>
        <type>long</type>
        <length>1</length>
        <name>Final Height</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>4148</code>
        <type>int</type>
        <length>1</length>
        <name>Compression Ratio</name>
        <example></example>
        <description></description>
    </tag>
</directory>
