=== Nuix/jrawio-src/jrawio/src/main/metadata/Directory.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
    <xsd:element name="directory">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="tag" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="code">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:nonNegativeInteger">
                                            <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="type">  
                                <xsd:simpleType>                                    
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="byte"/>
                                        <xsd:enumeration value="signed byte"/>
                                        <xsd:enumeration value="short"/>
                                        <xsd:enumeration value="signed short"/>
                                        <xsd:enumeration value="int"/>
                                        <xsd:enumeration value="signed int"/>
                                        <xsd:enumeration value="long"/>
                                        <xsd:enumeration value="signed long"/>
                                        <xsd:enumeration value="float"/>
                                        <xsd:enumeration value="double"/>
                                        <xsd:enumeration value="rational"/>
                                        <xsd:enumeration value="signed rational"/>
                                        <xsd:enumeration value="ascii"/>
                                        <xsd:enumeration value="undefined"/>
                                    </xsd:restriction> 
                                </xsd:simpleType>
                            </xsd:element>            
                            <xsd:element name="length" type="xsd:positiveInteger"  minOccurs="0"/>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="example" type="xsd:string"/>
                            <xsd:element name="models" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="model" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="enumeration" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="item" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="value">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="identifier" type="xsd:string"  minOccurs="0"/>
                                                    <xsd:element name="short-description" type="xsd:string"  minOccurs="0"/>
                                                    <xsd:element name="description" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="bitmask" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="item" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="value">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="base" type="xsd:positiveInteger" default="10"/>
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="identifier" type="xsd:string"/>
                                                    <xsd:element name="short-description" type="xsd:string"/>
                                                    <xsd:element name="description" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="description" type="xsd:string"/>
                        </xsd:sequence>
                        <xsd:attribute name="status" default="good">  
                            <xsd:simpleType>                                    
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="unknown"/>
                                    <xsd:enumeration value="uncertain"/>
                                    <xsd:enumeration value="incomplete"/>
                                    <xsd:enumeration value="volatile"/>
                                    <xsd:enumeration value="good"/>
                                </xsd:restriction> 
                            </xsd:simpleType>
                        </xsd:attribute>            
                    </xsd:complexType>
                </xsd:element>                
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nuix/jrawio-src/jrawio/metadata/LeicaMakerNote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="Leica" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>1</code>
        <type>short</type>
        <length>1</length>
        <name>CompressionRate</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>2</value>
                <description>Low</description>
            </item>
            <item>
                <value>3</value>
                <description>Normal</description>
            </item>
            <item>
                <value>6</value>
                <description>Very low</description>
            </item>
            <item>
                <value>7</value>
                <description>Raw</description>
            </item>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
    <tag>
        <code>3</code>
        <type>short</type>
        <length>1</length>
        <name>WhiteBalance</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>1</value>
                <description>Auto</description>
            </item>
            <item>
                <value>2</value>
                <description>Sunshine</description>
            </item>
            <item>
                <value>3</value>
                <description>Cloudy</description>
            </item>
            <item>
                <value>4</value>
                <description>Halogen</description>
            </item>
            <item>
                <value>5</value>
                <description>Manual</description>
            </item>
            <item>
                <value>8</value>
                <description>Electronic-Flash</description>
            </item>
            <item>
                <value>10</value>
                <description>Black-White</description>
            </item>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
    <tag>
        <code>7</code>
        <type>short</type>
        <length>1</length>
        <name>FocusMode</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>1</value>
                <description>Auto</description>
            </item>
        </enumeration>
        <enumeration>
            <item>
                <value>2</value>
                <description>Manual</description>
            </item>
        </enumeration>
        <enumeration>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
    <tag>
        <code>13</code>
        <type>short</type>
        <length></length>
        <name>LeikaWhiteBalance</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>15</code>
        <type>short</type>
        <length>1</length>
        <name>Spot Autofocus</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>256</value>
                <description>On</description>
            </item>
            <item>
                <value>4096</value>
                <description>Off</description>
            </item>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
    <tag>
        <code>28</code>
        <type>short</type>
        <length>1</length>
        <name>MacroMode</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>31</code>
        <type>short</type>
        <length>1</length>
        <name>Aperture</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>6</value>
                <description>Auto</description>
            </item>
            <item>
                <value>7</value>
                <description>Manual</description>
            </item>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
    <tag>
        <code>36</code>
        <type>short</type>
        <length>1</length>
        <name>FlashEV</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>44</code>
        <type>short</type>
        <length>1</length>
        <name>Contrast</name>
        <example></example>
        <description></description>
        <enumeration>
            <item>
                <value>0x100</value>
                <description>Low</description>
            </item>
            <item>
                <value>0x110</value>
                <description>Standard</description>
            </item>
            <item>
                <value>0x120</value>
                <description>High</description>
            </item>
            <item>
                <value>-1</value>
                <description>Unknown</description>
            </item>
        </enumeration>
    </tag>
</directory>

=== Nuix/jrawio-src/jrawio/src/metadata/OlympusCameraSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="OlympusCameraSettings" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>257</code>
        <type>int</type>
        <length>1</length>
        <name>ThumbnailOffset</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>258</code>
        <type>int</type>
        <length>1</length>
        <name>ThumbnailSize</name>
        <example></example>
        <description></description>
    </tag>
</directory>

=== Nuix/jrawio-src/jrawio/src/main/metadata/OlympusImageProcessing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Copyright (C) 2003-2008 by Fabrizio Giudici
======================================================

This file is licensed under a Creative Common License.
http://creativecommons.org/licenses/by-sa/2.5
======================================================

-->
<directory name="OlympusImageProcessing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Directory.xsd">
    <tag>
        <code>256</code>
        <type>short</type>
        <length>2</length>
        <name>RBCoefficients</name>
        <example></example>
        <description></description>
    </tag>
    <tag>
        <code>1556</code>
        <type>int</type>
        <length>1</length>
        <name>ImageWidth</name>
        <example></example>
        <description>The width of the image for E-510</description>
    </tag>
    <tag>
        <code>1557</code>
        <type>int</type>
        <length>1</length>
        <name>ImageHeight</name>
        <example></example>
        <description>The height of the image for E-510</description>
    </tag>
</directory>
